### ISSUE TITLE
Send email to admins whenever an error ocurs

### ISSUE THREAD

**Issue by OscarPDR** [OscarPDR/labman_ud#128]

**Comment by porduna** [comment]
An error where? Right now HTTP 500 already send e-mails. You mean when importing publications?

**Comment by aitoralmeida** [comment]
We should also send emails when there is any problem retrieving or adding a publication.

**Comment by OscarPDR** [comment]
Actually, logger.error could handle this issues by assigning an AdminEmailHandler log handler
